"""empty message

Revision ID: 88f643553b1e
Revises: cd3c7c7ab230
Create Date: 2018-09-25 02:36:55.750007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f643553b1e'
down_revision = 'cd3c7c7ab230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text', 'description')
    # ### end Alembic commands ###
