"""empty message

Revision ID: cd3c7c7ab230
Revises: 1142dc1042dc
Create Date: 2018-09-25 02:33:53.204452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd3c7c7ab230'
down_revision = '1142dc1042dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text', sa.Column('origin_language', sa.String(), nullable=False))
    op.add_column('text', sa.Column('requested_language', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text', 'requested_language')
    op.drop_column('text', 'origin_language')
    # ### end Alembic commands ###
